apiVersion: v1
kind: Service
metadata:
  name: matchingRecommendation
  labels:
    app: matchingRecommendation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matchingRecommendation