server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: userProfile
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: matchingRecommendation
          uri: http://localhost:8083
          predicates:
            - Path=/recommendations/**, 
        - id: chatFunctionality
          uri: http://localhost:8085
          predicates:
            - Path=/chats/**, 
        - id: locationService
          uri: http://localhost:8088
          predicates:
            - Path=/locations/**, 
        - id: paymentService
          uri: http://localhost:8092
          predicates:
            - Path=/payments/**, 
        - id: feedbackService
          uri: http://localhost:8097
          predicates:
            - Path=/feedbacks/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: userProfile
          uri: http://userProfile:8080
          predicates:
            - Path=/users/**, 
        - id: matchingRecommendation
          uri: http://matchingRecommendation:8080
          predicates:
            - Path=/recommendations/**, 
        - id: chatFunctionality
          uri: http://chatFunctionality:8080
          predicates:
            - Path=/chats/**, 
        - id: locationService
          uri: http://locationService:8080
          predicates:
            - Path=/locations/**, 
        - id: paymentService
          uri: http://paymentService:8080
          predicates:
            - Path=/payments/**, 
        - id: feedbackService
          uri: http://feedbackService:8080
          predicates:
            - Path=/feedbacks/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
