---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userProfile
  labels:
    app: userProfile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userProfile
  template:
    metadata:
      labels:
        app: userProfile
    spec:
      containers:
        - name: userProfile
          image: username/userProfile:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchingRecommendation
  labels:
    app: matchingRecommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchingRecommendation
  template:
    metadata:
      labels:
        app: matchingRecommendation
    spec:
      containers:
        - name: matchingRecommendation
          image: username/matchingRecommendation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatFunctionality
  labels:
    app: chatFunctionality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatFunctionality
  template:
    metadata:
      labels:
        app: chatFunctionality
    spec:
      containers:
        - name: chatFunctionality
          image: username/chatFunctionality:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: locationService
  labels:
    app: locationService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locationService
  template:
    metadata:
      labels:
        app: locationService
    spec:
      containers:
        - name: locationService
          image: username/locationService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentService
  labels:
    app: paymentService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentService
  template:
    metadata:
      labels:
        app: paymentService
    spec:
      containers:
        - name: paymentService
          image: username/paymentService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedbackService
  labels:
    app: feedbackService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedbackService
  template:
    metadata:
      labels:
        app: feedbackService
    spec:
      containers:
        - name: feedbackService
          image: username/feedbackService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: userProfile
  labels:
    app: userProfile
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: userProfile


---


apiVersion: v1
kind: Service
metadata:
  name: matchingRecommendation
  labels:
    app: matchingRecommendation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matchingRecommendation


---


apiVersion: v1
kind: Service
metadata:
  name: chatFunctionality
  labels:
    app: chatFunctionality
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chatFunctionality


---


apiVersion: v1
kind: Service
metadata:
  name: locationService
  labels:
    app: locationService
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: locationService


---


apiVersion: v1
kind: Service
metadata:
  name: paymentService
  labels:
    app: paymentService
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: paymentService


---


apiVersion: v1
kind: Service
metadata:
  name: feedbackService
  labels:
    app: feedbackService
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: feedbackService

